/*Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*Loyalty Benefits API
 * The Loyalty Benefits API provides benefits management including presentment and selection.  It also supports insurance certificate generation for insurance benefits that need certificates.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.*/
package com.mastercard.developer.example;

import java.util.ArrayList;
import java.util.List;

import com.mastercard.developer.interceptors.OkHttp2OAuth1Interceptor;
import com.mastercard.developer.loyalty_benefits_client.ApiClient;
import com.mastercard.developer.loyalty_benefits_client.ApiException;
import com.mastercard.developer.loyalty_benefits_client.api.BenefitsApi;
import com.mastercard.developer.loyalty_benefits_client.api.BundleProfileApi;
import com.mastercard.developer.loyalty_benefits_client.api.InsuranceApi;
import com.mastercard.developer.loyalty_benefits_client.model.Account;
import com.mastercard.developer.loyalty_benefits_client.model.AccountExternal;
import com.mastercard.developer.loyalty_benefits_client.model.Address;
import com.mastercard.developer.loyalty_benefits_client.model.AssignedBenefits;
import com.mastercard.developer.loyalty_benefits_client.model.Benefits;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitsSelection;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitsSelectionAdditionalInformation;
import com.mastercard.developer.loyalty_benefits_client.model.BilheteRequestAdditionalInformationCardholder;
import com.mastercard.developer.loyalty_benefits_client.model.BilheteRequestAdditionalInformationDependents;
import com.mastercard.developer.loyalty_benefits_client.model.BilheteRequestAdditionalInformationPartner;
import com.mastercard.developer.loyalty_benefits_client.model.BundleUser;
import com.mastercard.developer.loyalty_benefits_client.model.BundleUserData;
import com.mastercard.developer.loyalty_benefits_client.model.BundleUserResponse;
import com.mastercard.developer.loyalty_benefits_client.model.ClaimStatus;
import com.mastercard.developer.loyalty_benefits_client.model.ClaimStatusRequest;
import com.mastercard.developer.loyalty_benefits_client.model.Consent;
import com.mastercard.developer.loyalty_benefits_client.model.Credentials;
import com.mastercard.developer.loyalty_benefits_client.model.Email;
import com.mastercard.developer.loyalty_benefits_client.model.Identification;
import com.mastercard.developer.loyalty_benefits_client.model.Im;
import com.mastercard.developer.loyalty_benefits_client.model.Name;
import com.mastercard.developer.loyalty_benefits_client.model.PhoneNumber;
import com.mastercard.developer.loyalty_benefits_client.model.Photo;
import com.mastercard.developer.loyalty_benefits_client.model.SubmitClaimUserData;
import com.mastercard.developer.loyalty_benefits_client.model.SubmitClaimUserToken;
import com.mastercard.developer.loyalty_benefits_client.model.User;
import com.mastercard.developer.loyalty_benefits_client.model.UserProduct;

public class BenefitsApiDemo {

	public static void main(String[] args) throws Exception {

		RequestHelper.loadProperties();

		ApiClient apiClient = new ApiClient();
		apiClient.setBasePath(RequestHelper.getBaseURL());
		apiClient.getHttpClient().interceptors()
				.add(new OkHttp2OAuth1Interceptor(RequestHelper.getConsumerkey(), RequestHelper.getPrivateKey()));
		apiClient.setDebugging(true);
		
		BenefitsApi benefitsApi = new BenefitsApi(apiClient);

		InsuranceApi insuranceApi = new InsuranceApi(apiClient);
		
		if(runThisScenario(args,"registration")) {
			BundleProfileApi bundleProfileApi = new BundleProfileApi(apiClient);
			executeRegistrationScenario(bundleProfileApi);
		}
		
		if(runThisScenario(args,"getbenefits")) {
			executeBenefitsRetrieveScenario(benefitsApi);
		}

		if(runThisScenario(args,"selectbenefits")) {
			executeBenefitSelectionScenario(benefitsApi);
		}

		if(runThisScenario(args,"assignedbenefits")) {
			executeAssignedBenefitsRetrieveScenario(benefitsApi);
		}

		if(runThisScenario(args,"claimsearch")) {
			executeInsuranceClaimSearchScenario(insuranceApi);
		}
		
		if(runThisScenario(args,"insurancetoken")) {
			executeInsuranceTokenDataScenario(insuranceApi);
		}

		if(runThisScenario(args,"error")) {
			executeBenefitsRetrieveErrorScenario(benefitsApi);
		}
	}

	private static void executeRegistrationScenario(BundleProfileApi bundleProfileApi) {
		BundleUser bundleUser = getRegistrationObject();
		try {
			printMessage("STARTING BENEFITS REGISTRATION FROM COMMAND LINE RUNNER");
			BundleUserResponse result = bundleProfileApi.createUser(bundleUser);
			System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Benefits Registration");
			e.printStackTrace();
		}
	}

	private static void executeBenefitsRetrieveScenario(BenefitsApi benefitsApi) {
		Integer ica = 1216;
		String productName = "black";
		String channel = "web";
		String preferredLanguage = "pt-BR";
		try {
			printMessage("STARTING GET AVAILABLE BENEFITS FROM COMMAND LINE RUNNER");
			Benefits result = benefitsApi.loyaltyBenefitsProductBenefitsGet(ica, productName, channel,
					preferredLanguage);
			System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Get Benefits");
			e.printStackTrace();
		}
	}

	private static void executeBenefitSelectionScenario(BenefitsApi benefitsApi) {
		BenefitsSelection benefitsSelection = getBenefitSelectionObject();
		try {
			printMessage("STARTING BENEFITS SELECTION FROM COMMAND LINE RUNNER");
			benefitsApi.loyaltyBenefitsBenefitSelectionsPost(benefitsSelection);
			System.out.println("Benefit Selection Successfull");
		} catch (Exception e) {
			System.err.println("Exception while Benefit Selection");
			e.printStackTrace();
		}
	}

	private static void executeAssignedBenefitsRetrieveScenario(BenefitsApi benefitsApi) {
		Integer ica = 1216;
		String panLastFourDigits = "2244";
		String channel = "tablet";
		String preferredLanguage = "en-GB";
		String userId = "user1235";
		try {
			printMessage("STARTING GET ASSIGNED BENEFITS FROM COMMAND LINE RUNNER");
			AssignedBenefits result = benefitsApi.loyaltyBenefitsAssignedBenefitsGet(ica, userId, panLastFourDigits,
					channel, preferredLanguage);
			System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Assigned Benefits");
			e.printStackTrace();
		}
	}

	private static void executeInsuranceClaimSearchScenario(InsuranceApi insuranceApi) {
		ClaimStatusRequest claimStatusRequest = new ClaimStatusRequest("C0011", "71000", "English");
		try {
			printMessage("STARTING INSURANCE CLAIM SEARCH FROM COMMAND LINE RUNNER");
			ClaimStatus result = insuranceApi.loyaltyInsuranceClaimSearchesPost(claimStatusRequest);
			System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception in Insurance Claim Search");
			e.printStackTrace();
		}
	}
	
	private static void executeInsuranceTokenDataScenario(InsuranceApi insuranceApi) {
		
		SubmitClaimUserData submitClaimUserData = new SubmitClaimUserData();
		submitClaimUserData.setFirstName("John");
		submitClaimUserData.setLastName("Smith");
		submitClaimUserData.setState("SP");
		submitClaimUserData.setPan("50000000000000000");

		try {
			printMessage("STARTING INSURANCE TOKENIZE DATA FROM COMMAND LINE RUNNER");
			SubmitClaimUserToken result = insuranceApi.loyaltyInsuranceUserDataTokensPost(submitClaimUserData);
			System.out.println("Parsed Response---------------");
			System.out.println("Token: "+result);
		} catch (Exception e) {
			System.err.println("Exception in Insurance Token Data");
			e.printStackTrace();
		}
	}
	
	private static void executeBenefitsRetrieveErrorScenario(BenefitsApi benefitsApi) {
		Integer ica = 1;
		String productName = "KWrkp2V4c";
		String channel = "rpBLflhhahT";
		String preferredLanguage = "Mvr2Avshto";
		try {
			printMessage("STARTING GET AVAILABLE BENEFITS ERROR SCENARIO FROM COMMAND LINE RUNNER");
			benefitsApi.loyaltyBenefitsProductBenefitsGet(ica, productName, channel,
					preferredLanguage);
		} catch (ApiException e) {
			System.err.println("Exception when calling BenefitsApi#GetBenefits");
			System.out.println("Parsed Response---------------");
			System.out.println(e.getResponseBody());
		}
	}

	private static void printMessage(String scenario) {
		System.out.println("--------------------------------------------------------------------");
		System.out.println("--------------------------------------------------------------------");
		System.out.println(scenario + "---------------");
		System.out.println("--------------------------------------------------------------------");
		System.out.println("--------------------------------------------------------------------");
	}

	private static BenefitsSelection getBenefitSelectionObject() {

		BenefitsSelection benefitsSelection = new BenefitsSelection();
		benefitsSelection.setUserId("user1235");
		benefitsSelection.setPanLastFourDigits("2244");
		benefitsSelection.setIca(1216);
		benefitsSelection.setCardProductType("Black");
		benefitsSelection.setMemberId("3154");

		List<String> benefitIds = new ArrayList<>();
		benefitIds.add("BEN7890");
		benefitsSelection.setBenefitIds(benefitIds);

		BenefitsSelectionAdditionalInformation additionalInformation = new BenefitsSelectionAdditionalInformation();
		additionalInformation.setCardholder(new BilheteRequestAdditionalInformationCardholder("John", "Smith",
				"1992-02-02", "BRA", "999.999.999-99", "Rua Francisco Pereira da Silva 1480", "Guarulhos", "SP",
				"1930288", "Parque Paulistano", "john.smith@mail.com", "11", "1111-1111"));
		additionalInformation.setPartner(
				new BilheteRequestAdditionalInformationPartner("John", "Smith", "999.999.999-99", "1992-02-02"));
		List<BilheteRequestAdditionalInformationDependents> dependents = new ArrayList<>();
		dependents.add(
				new BilheteRequestAdditionalInformationDependents("John", "Smith", "999.999.999-99", "1991-01-02"));
		additionalInformation.setDependents(dependents);
		benefitsSelection.setAdditionalInformation(getAdditionalInformation());

		return benefitsSelection;

	}

	private static BenefitsSelectionAdditionalInformation getAdditionalInformation() {
		BenefitsSelectionAdditionalInformation additionalInformation = new BenefitsSelectionAdditionalInformation();
		additionalInformation.setCardholder(new BilheteRequestAdditionalInformationCardholder("John", "Smith",
				"1992-02-02", "BRA", "999.999.999-99", "Rua Francisco Pereira da Silva 1480", "Guarulhos", "SP",
				"1930288", "Parque Paulistano", "john.smith@mail.com", "11", "1111-1111"));
		additionalInformation.setPartner(
				new BilheteRequestAdditionalInformationPartner("John", "Smith", "999.999.999-99", "1992-02-02"));
		List<BilheteRequestAdditionalInformationDependents> dependents = new ArrayList<>();
		dependents.add(
				new BilheteRequestAdditionalInformationDependents("John", "Smith", "999.999.999-99", "1991-01-02"));
		additionalInformation.setDependents(dependents);
		return additionalInformation;
	}

	private static BundleUser getRegistrationObject() {
		BundleUser bundleUser = new BundleUser();
		BundleUserData bundleUserData = new BundleUserData();
		User user = new User();
		UserProduct userProduct = new UserProduct();
		Address address = new Address();
		Email email = new Email();
		Identification identification = new Identification();
		Im im = new Im();
		Name name = new Name();
		PhoneNumber phoneNumber = new PhoneNumber();
		Photo photo = new Photo();
		List<Photo> photos = new ArrayList<>();
		List<PhoneNumber> phoneNumbers = new ArrayList<>();
		List<Im> ims = new ArrayList<>();
		List<Identification> identifications = new ArrayList<>();
		List<Email> emails = new ArrayList<>();
		List<Address> addresses = new ArrayList<>();

		user.setActive(true);
		address.setCountry("US");
		address.setFormatted("114 5th Ave, New York, NY 10011");
		address.setLocality("city");
		address.setOperation("None");
		address.setPostalCode("10011");
		address.setPrimary(false);
		address.setRegion("NY");
		address.setStreetAddress("114 5th Ave");
		address.setStreetAddress2("Suite 20");
		address.setType("work");
		addresses.add(address);
		user.setAddresses(addresses);

		user.setDateOfBirth("1992-11-17");
		user.setDisplayName("John F Smith");

		email.setDisplay("Primary email address of user");
		email.setOperation("None");
		email.setPrimary(true);
		email.setType("home");
		email.setValue("john5033379289074369@gmail.com");
		emails.add(email);
		user.setEmails(emails);

		user.setExternalId("user123-partnerBank");
		user.setId("d3459481-fb1c-48bb-8685-40eb629e2ae1");

		identification.setCountry("BR");
		identification.setType("CPF");
		identification.setValue("496881234");
		identifications.add(identification);
		user.setIdentifications(identifications);

		im.setDisplay("user Yahoo-id");
		im.setOperation("None");
		im.setPrimary(true);
		im.setType("aim");
		im.setValue("JohnFSmith123");
		ims.add(im);
		user.setIms(ims);

		user.locale("en-US");

		name.setFamilyName("Smitherines");
		name.setFormatted("Sally Smitherines");
		name.setGivenName("Sally");
		name.setHonorificPrefix("Ms.");
		name.setHonorificSuffix("Sr.");
		name.setMiddleName("F");
		user.setName(name);

		user.setNickName("sallySmith");
		user.setPassword("boingouser5105363487498185");

		phoneNumber.setDisplay("Office fax of user");
		phoneNumber.setOperation("None");
		phoneNumber.setPrimary(false);
		phoneNumber.setType("fax");
		phoneNumber.setValue("+1-201-555-0123");
		phoneNumbers.add(phoneNumber);
		user.setPhoneNumbers(phoneNumbers);

		photo.setDisplay("portrait");
		photo.setOperation("None");
		photo.setPrimary(true);
		photo.setType("thumbnail");
		photo.setValue("facebook.com/JohnFSmith123/photos/1");
		photos.add(photo);
		user.setPhotos(photos);

		user.setPreferredLanguage("en");
		user.setProfileUrl("facebook.com/JohnFSmith123");
		user.setTimezone("America/New_York");
		user.setTitle("Vice President");
		user.setUserId("user123-partnerBank");
		user.setUserName("JohnFSmith123");
		user.setUserType("Intern");

		Account account = new Account();
		account.setAccountType("SingleMember");
		account.setBrand("Mastercard");
		account.setCardAlias("d3459481-fb1c-48bb-8685-40eb629e2ae1");
		account.setCardExpiryDate("02/2024");
		account.setCvcCode("876");
		account.setIca(12594L);
		account.setLast4Pan(8185);
		account.setNameOnCard("SALLY SMITHERINES");
		account.setPan("5105363487498185");
		account.setPar("q1hjz28rka1ebl470g9xyg90r5d3e");
		account.setPrimary(true);
		account.setProductLine("Credit cards");
		account.setProductType("Black");
		account.setUuid("d3459481-fb1c-48bb-8685-40eb629e2ae1");

		AccountExternal accountExternal = new AccountExternal();
		accountExternal.setAccountStatusCode("1");
		accountExternal.setExternalMembershipReferenceId("B12345");
		account.setObject(accountExternal);

		Consent consent = new Consent();
		consent.setAgreed(true);
		consent.setConsentType("author-legal-content-document");
		consent.setConsentedDate("2018-06-19T12:30:42.307+0000");
		consent.setCountry("BRA");
		consent.setLanguage("en_us");
		consent.setServiceCode("priceless");
		consent.setServiceFunctionCode("registration-page code");
		consent.setUseCategoryCode("UC-01");
		consent.setUseCategoryValue("acceptPersonalizedOffersEmail");
		consent.setUuid("d3459481-fb1c-48bb-8685-40eb629e2ae1");

		List<Account> accounts = new ArrayList<>();
		accounts.add(account);
		List<Consent> consents = new ArrayList<>();
		consents.add(consent);
		Credentials productCredentials = new Credentials();
		productCredentials.setUsername("boingoid123");
		productCredentials.setPassword("boingopwd");
		userProduct.setProduct("benefits");
		userProduct.setAccounts(accounts);
		userProduct.setConsents(consents);
		userProduct.setObject(productCredentials);
		List<UserProduct> products = new ArrayList<>();
		products.add(userProduct);

		bundleUserData.setProducts(products);
		bundleUserData.setUser(user);
		bundleUser.setData(bundleUserData);

		return bundleUser;

	}

	private static boolean runThisScenario(String[] args, String scenario) {
		return (args!=null && args.length>0 && args[0].contains(scenario)) || (args == null || args.length == 0);
	}
}
