/*
 * Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * Loyalty Benefits API
 * The Loyalty Benefits API provides benefits management including presentment and selection.  It also supports insurance certificate generation for insurance benefits that need certificates.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_benefits_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitAttribute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AssignedBenefit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-30T13:58:23.312-06:00[America/Chicago]")
public class AssignedBenefit {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ACTIVATION_DATE = "activationDate";
  @SerializedName(SERIALIZED_NAME_ACTIVATION_DATE)
  private String activationDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private String endDate;

  public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  private String imageUrl;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<BenefitAttribute> attributes = null;

  public AssignedBenefit id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique ID that corresponds to a benefit.
   * @return id
  **/
  @ApiModelProperty(example = "BEN7890", value = "A unique ID that corresponds to a benefit.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AssignedBenefit name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Benefit name
   * @return name
  **/
  @ApiModelProperty(example = "Travel Assistance", value = "Benefit name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssignedBenefit description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Benefit description
   * @return description
  **/
  @ApiModelProperty(example = "Travel Assistance", value = "Benefit description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AssignedBenefit activationDate(String activationDate) {
    this.activationDate = activationDate;
    return this;
  }

   /**
   * Date on which the benefit is/was activated
   * @return activationDate
  **/
  @ApiModelProperty(example = "2018-01-31", value = "Date on which the benefit is/was activated")
  public String getActivationDate() {
    return activationDate;
  }

  public void setActivationDate(String activationDate) {
    this.activationDate = activationDate;
  }

  public AssignedBenefit endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Date on which the benefit was/will deactivate
   * @return endDate
  **/
  @ApiModelProperty(example = "2019-01-30", value = "Date on which the benefit was/will deactivate")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public AssignedBenefit imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Representative image for the benefit
   * @return imageUrl
  **/
  @ApiModelProperty(example = "http://example.url.com/...", value = "Representative image for the benefit")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public AssignedBenefit attributes(List<BenefitAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public AssignedBenefit addAttributesItem(BenefitAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<BenefitAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Array of attributes applicable to this benefit
   * @return attributes
  **/
  @ApiModelProperty(value = "Array of attributes applicable to this benefit")
  public List<BenefitAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<BenefitAttribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedBenefit assignedBenefit = (AssignedBenefit) o;
    return Objects.equals(this.id, assignedBenefit.id) &&
        Objects.equals(this.name, assignedBenefit.name) &&
        Objects.equals(this.description, assignedBenefit.description) &&
        Objects.equals(this.activationDate, assignedBenefit.activationDate) &&
        Objects.equals(this.endDate, assignedBenefit.endDate) &&
        Objects.equals(this.imageUrl, assignedBenefit.imageUrl) &&
        Objects.equals(this.attributes, assignedBenefit.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, activationDate, endDate, imageUrl, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignedBenefit {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    activationDate: ").append(toIndentedString(activationDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

