/*
 * Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * Loyalty Benefits API
 * The Loyalty Benefits API provides benefits management including presentment and selection.  It also supports insurance certificate generation for insurance benefits that need certificates.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_benefits_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.loyalty_benefits_client.model.AssignedBenefitSubCategory;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AssignedBenefitCategory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-30T13:58:23.312-06:00[America/Chicago]")
public class AssignedBenefitCategory {
  public static final String SERIALIZED_NAME_CATEGORY_NAME = "categoryName";
  @SerializedName(SERIALIZED_NAME_CATEGORY_NAME)
  private String categoryName;

  public static final String SERIALIZED_NAME_CATEGORY_DESCRIPTION = "categoryDescription";
  @SerializedName(SERIALIZED_NAME_CATEGORY_DESCRIPTION)
  private String categoryDescription;

  public static final String SERIALIZED_NAME_SUB_CATEGORIES = "subCategories";
  @SerializedName(SERIALIZED_NAME_SUB_CATEGORIES)
  private List<AssignedBenefitSubCategory> subCategories = null;

  public AssignedBenefitCategory categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Benefit category name
   * @return categoryName
  **/
  @ApiModelProperty(example = "Travel", value = "Benefit category name")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public AssignedBenefitCategory categoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
    return this;
  }

   /**
   * Benefit category description
   * @return categoryDescription
  **/
  @ApiModelProperty(example = "Travel and Experiences", value = "Benefit category description")
  public String getCategoryDescription() {
    return categoryDescription;
  }

  public void setCategoryDescription(String categoryDescription) {
    this.categoryDescription = categoryDescription;
  }

  public AssignedBenefitCategory subCategories(List<AssignedBenefitSubCategory> subCategories) {
    this.subCategories = subCategories;
    return this;
  }

  public AssignedBenefitCategory addSubCategoriesItem(AssignedBenefitSubCategory subCategoriesItem) {
    if (this.subCategories == null) {
      this.subCategories = new ArrayList<AssignedBenefitSubCategory>();
    }
    this.subCategories.add(subCategoriesItem);
    return this;
  }

   /**
   * Array of sub-categories within this category
   * @return subCategories
  **/
  @ApiModelProperty(value = "Array of sub-categories within this category")
  public List<AssignedBenefitSubCategory> getSubCategories() {
    return subCategories;
  }

  public void setSubCategories(List<AssignedBenefitSubCategory> subCategories) {
    this.subCategories = subCategories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedBenefitCategory assignedBenefitCategory = (AssignedBenefitCategory) o;
    return Objects.equals(this.categoryName, assignedBenefitCategory.categoryName) &&
        Objects.equals(this.categoryDescription, assignedBenefitCategory.categoryDescription) &&
        Objects.equals(this.subCategories, assignedBenefitCategory.subCategories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryName, categoryDescription, subCategories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignedBenefitCategory {\n");
    
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    categoryDescription: ").append(toIndentedString(categoryDescription)).append("\n");
    sb.append("    subCategories: ").append(toIndentedString(subCategories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

