/*
 * Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * Loyalty Benefits API
 * The Loyalty Benefits API provides benefits management including presentment and selection.  It also supports insurance certificate generation for insurance benefits that need certificates.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_benefits_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitAttribute;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitDetailContent;
import com.mastercard.developer.loyalty_benefits_client.model.BenefitDocuments;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BenefitDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-30T13:58:23.312-06:00[America/Chicago]")
public class BenefitDetail {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION_SHORT = "descriptionShort";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_SHORT)
  private String descriptionShort;

  public static final String SERIALIZED_NAME_DESCRIPTION_LONG = "descriptionLong";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_LONG)
  private String descriptionLong;

  public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  private String imageUrl;

  public static final String SERIALIZED_NAME_FAQ_URL = "faqUrl";
  @SerializedName(SERIALIZED_NAME_FAQ_URL)
  private String faqUrl;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private BenefitDetailContent content = null;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<BenefitAttribute> attributes = null;

  public static final String SERIALIZED_NAME_DOCUMENTS = "documents";
  @SerializedName(SERIALIZED_NAME_DOCUMENTS)
  private List<BenefitDocuments> documents = null;

  public BenefitDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Benefit unique identifier
   * @return id
  **/
  @ApiModelProperty(example = "BEN7890", value = "Benefit unique identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BenefitDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Benefit name
   * @return name
  **/
  @ApiModelProperty(example = "Travel Assistance", value = "Benefit name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BenefitDetail descriptionShort(String descriptionShort) {
    this.descriptionShort = descriptionShort;
    return this;
  }

   /**
   * Benefit short description
   * @return descriptionShort
  **/
  @ApiModelProperty(example = "Travel Assistance", value = "Benefit short description")
  public String getDescriptionShort() {
    return descriptionShort;
  }

  public void setDescriptionShort(String descriptionShort) {
    this.descriptionShort = descriptionShort;
  }

  public BenefitDetail descriptionLong(String descriptionLong) {
    this.descriptionLong = descriptionLong;
    return this;
  }

   /**
   * Detailed description for a benefit
   * @return descriptionLong
  **/
  @ApiModelProperty(example = "Travel Assistance provides 24 hour ...", value = "Detailed description for a benefit")
  public String getDescriptionLong() {
    return descriptionLong;
  }

  public void setDescriptionLong(String descriptionLong) {
    this.descriptionLong = descriptionLong;
  }

  public BenefitDetail imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Representative image for the benefit
   * @return imageUrl
  **/
  @ApiModelProperty(example = "http://example.url.com/...", value = "Representative image for the benefit")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public BenefitDetail faqUrl(String faqUrl) {
    this.faqUrl = faqUrl;
    return this;
  }

   /**
   * URL to  Frequently Asked Questions about the benefit
   * @return faqUrl
  **/
  @ApiModelProperty(example = "http://example.url.com/...", value = "URL to  Frequently Asked Questions about the benefit")
  public String getFaqUrl() {
    return faqUrl;
  }

  public void setFaqUrl(String faqUrl) {
    this.faqUrl = faqUrl;
  }

  public BenefitDetail content(BenefitDetailContent content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public BenefitDetailContent getContent() {
    return content;
  }

  public void setContent(BenefitDetailContent content) {
    this.content = content;
  }

  public BenefitDetail attributes(List<BenefitAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public BenefitDetail addAttributesItem(BenefitAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<BenefitAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Array of attributes applicable to this benefit
   * @return attributes
  **/
  @ApiModelProperty(value = "Array of attributes applicable to this benefit")
  public List<BenefitAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<BenefitAttribute> attributes) {
    this.attributes = attributes;
  }

  public BenefitDetail documents(List<BenefitDocuments> documents) {
    this.documents = documents;
    return this;
  }

  public BenefitDetail addDocumentsItem(BenefitDocuments documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<BenefitDocuments>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Benefit Terms and Privacy URL&#39;s
   * @return documents
  **/
  @ApiModelProperty(value = "Benefit Terms and Privacy URL's")
  public List<BenefitDocuments> getDocuments() {
    return documents;
  }

  public void setDocuments(List<BenefitDocuments> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BenefitDetail benefitDetail = (BenefitDetail) o;
    return Objects.equals(this.id, benefitDetail.id) &&
        Objects.equals(this.name, benefitDetail.name) &&
        Objects.equals(this.descriptionShort, benefitDetail.descriptionShort) &&
        Objects.equals(this.descriptionLong, benefitDetail.descriptionLong) &&
        Objects.equals(this.imageUrl, benefitDetail.imageUrl) &&
        Objects.equals(this.faqUrl, benefitDetail.faqUrl) &&
        Objects.equals(this.content, benefitDetail.content) &&
        Objects.equals(this.attributes, benefitDetail.attributes) &&
        Objects.equals(this.documents, benefitDetail.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, descriptionShort, descriptionLong, imageUrl, faqUrl, content, attributes, documents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BenefitDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    descriptionShort: ").append(toIndentedString(descriptionShort)).append("\n");
    sb.append("    descriptionLong: ").append(toIndentedString(descriptionLong)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    faqUrl: ").append(toIndentedString(faqUrl)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

