/*Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * Loyalty Benefits API
 * The Loyalty Benefits API provides benefits management including presentment and selection.  It also supports insurance certificate generation for insurance benefits that need certificates.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.loyalty_benefits_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RequiredClaimDocuments
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-30T13:58:23.312-06:00[America/Chicago]")
public class RequiredClaimDocuments {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_IS_RECEIVED = "isReceived";
  @SerializedName(SERIALIZED_NAME_IS_RECEIVED)
  private Boolean isReceived;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public RequiredClaimDocuments name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Insurance claim required document name
   * @return name
  **/
  @ApiModelProperty(example = "Purchase Receipt", value = "Insurance claim required document name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RequiredClaimDocuments description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Insurance claim required document description
   * @return description
  **/
  @ApiModelProperty(example = "Receipt from the merchant on the date of purchase.", value = "Insurance claim required document description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RequiredClaimDocuments isReceived(Boolean isReceived) {
    this.isReceived = isReceived;
    return this;
  }

   /**
   * Insurance claim required document received indicator
   * @return isReceived
  **/
  @ApiModelProperty(example = "false", value = "Insurance claim required document received indicator")
  public Boolean getIsReceived() {
    return isReceived;
  }

  public void setIsReceived(Boolean isReceived) {
    this.isReceived = isReceived;
  }

  public RequiredClaimDocuments category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Insurance claim required document category
   * @return category
  **/
  @ApiModelProperty(example = "Travel", value = "Insurance claim required document category")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequiredClaimDocuments requiredClaimDocuments = (RequiredClaimDocuments) o;
    return Objects.equals(this.name, requiredClaimDocuments.name) &&
        Objects.equals(this.description, requiredClaimDocuments.description) &&
        Objects.equals(this.isReceived, requiredClaimDocuments.isReceived) &&
        Objects.equals(this.category, requiredClaimDocuments.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, isReceived, category);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequiredClaimDocuments {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isReceived: ").append(toIndentedString(isReceived)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

